---
title: 'Unit 11: Modeling Financial Data'
author: "Thejas Prasad"
date: "11/6/2017"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Unit 11 Lecture Assignment

```{r SP500, echo=TRUE, fig.height=10,fig.width=15 }
#install.packages("tseries")

library(tseries)
library(printr) # To give a table view

## S&P 500 (^GSPC)
###    SNP - SNP Real Time Price. Currency in USD

# Download the data of SP500 '^gspc'.
SNPdata <- get.hist.quote('^gspc',quote="Close")

length(SNPdata)

# Calculate the log returns, which is the subtraction of log(lag(SNPdata)) and log(SNPdata)
SNPret <- log(lag(SNPdata)) - log(SNPdata)

length(SNPret)

# Calculate volatility measure that is to multiply sd(SNPret),sqrt(250), 100
SNPvol <- sd(SNPret) * sqrt(250) * 100
SNPvol

## Define getVol function for volatility
getVol <- function(d, logrets) {
	var = 0
	lam = 0
	varlist <- c()

	for (r in logrets) {
		lam = lam*(1 - 1/d) + 1
	  var = (1 - 1/lam)*var + (1/lam)*r^2
		varlist <- c(varlist, var)
	}

	sqrt(varlist)
}

# Calculate volatility over entire length of series for various three different decay factors: 10 30. 100

# call getVol function with the parameters: 10,SNPret
volest <- getVol(10, SNPret)

# call getVol function with the parameters: 30,SNPret
volest2 <- getVol(30, SNPret)

# call getVol function with the parameters: 100,SNPret
volest3 <- getVol(100, SNPret)

# Plot the results, overlaying the volatility curves on the data, just as was done in the S&P example.
plot(volest,type="l")

# Add connected line segments for volest2 with the parameters: type="l",col="red"
lines(volest2, type = "l", col ="red")

# Add connected line segments for volest3 with the parameters: type="l",col="blue"
lines(volest3, type = "l", col ="blue")

```

